### ISSUE TITLE
Lowest deps error

### ISSUE THREAD

**Issue by soullivaneuh** [sonata-project/SonataPropelAdminBundle#64]
```
require_once(phing/Project.php): failed to open stream: No such file or directory
```

Job: https://travis-ci.org/sonata-project/SonataPropelAdminBundle/jobs/67001632

Can't get ride of this. Any idea?

**Comment by Soullivaneuh** [comment]
@K-Phoen maybe?

**Comment by K-Phoen** [comment]
Nope, no magical solution right now, sorry :/
