### ISSUE TITLE
Filter zero values problem

### ISSUE THREAD

**Issue by kosolapovvp** [sonata-project/SonataPropelAdminBundle#66]
Hi!
I have problem when filter values like 0, 0.0, etc.
Maybe we must change  **AbstractFilter::isActive** method to compare value with **null**?
From:

```
       return is_array($values) && !empty($values['value']);
```

To:

```
        return is_array($values) && isset($values['value']) && null !== $values['value'];
```

**Comment by Soullivaneuh** [comment]
Thanks for reporting.

Feel free to make a PR with relevant tests and fix. :+1:
