### ISSUE TITLE
Project ETA

### ISSUE THREAD

**Issue by Soullivaneuh** [sonata-project/SonataPropelAdminBundle#69]
I would like an ETA of this project.
- Is that still maintained?
- Is this compatible with admin-bundle 3.0 (old 2.4-dev)?
- Is master BC with actual `1.0.0` tag? (#62)

I would like to integrate it on dev-kit and start the new management release, this package is the last one except sandbox and ecommerce.

Thanks.

cc @rande @sonata-project/contributors 
cc @K-Phoen @dbu @havvg @lsmith77 @ClementGautier

**Comment by dbu** [comment]
i have nothing to do with propel, so no idea.

**Comment by K-Phoen** [comment]
I've not worked on this bundle for a long time so no idea either.

**Comment by Soullivaneuh** [comment]
> i have nothing to do with propel, so no idea.

@dbu Shall I remove you from the collaborators?

![image](https://cloud.githubusercontent.com/assets/1698357/15849802/8938985c-2c94-11e6-884c-561cbb7cdee7.png)

**Comment by dbu** [comment]
i wasn't aware i am contributor of this bundle. i assume i was just added to all sonata projects at some point. yes, you can remove me (as long as you leave me in the phpcr admin and the translation bundle ;-) )

**Comment by Soullivaneuh** [comment]
> i wasn't aware i am contributor of this bundle. i assume i was just added to all sonata projects at some point. yes, you can remove me (as long as you leave me in the phpcr admin and the translation bundle ;-) )

Will do that. This will avoid useless pings for you. :wink:

**Comment by vworldat** [comment]
@OskarStark not with highest priority, but in some legacy projects at least. I'm not fully sure yet whether I'll be using propel in the near future or not.

**Comment by OskarStark** [comment]
ok, thank you for your feedback @vworldat 👍

**Comment by Soullivaneuh** [comment]
Well, not a lot of people...

I can check code usage of admin-bundle and try to adapt it to push a new major, but I don't use propel at all so I can't check everything.

**Comment by rande** [comment]
@ClementGautier Can you add your input on this bundle

**Comment by Th3Mouk** [comment]
cc @Id4v

**Comment by Soullivaneuh** [comment]
To be clear: If we don't have any active contributor on this project, this one will be simply deprecated.

I'm agree to add it on dev-kit and make the refactor, but it will be painful to maintain it without any Propel specialist to help.

**Comment by ih84ds** [comment]
I am interested in this project. Have a symfony 2.8 project that desperately needs an propel admin backend. What is the status?

**Comment by Soullivaneuh** [comment]
@ih84ds Status: Need official contributors. :wink:

**Comment by heristop** [comment]
@Soullivaneuh I might take the suject within the next two months, if you want

**Comment by OskarStark** [comment]
Would be great to welcome you on board @heristop 👍

**Comment by mvhirsch** [comment]
In my opinion, this should be either maintained or not. So please let me be clear: 
There is hardly no development nor maintenance for [propel1](https://github.com/propelorm/Propel); an unpredictable future of a stable propel2 (alpha/beta for the last ~2 years with no clear end on the road) and the latter would require a rewrite of this package; an odd release management for the suggested [Propel<->Symfony Integration PropelBundle](https://github.com/propelorm/PropelBundle) ....

People still want to use this? Okay okay, so for long-maintained projects I'm okay with (heck I have to deal with something in similar). But for new projects, these requirements are more than tenuous for professional projects.

If there is no active help from community nor from maintainers (either both sides: propel _and_ sonata), I don't think Sonata should provide an integration for it anymore. This of course does not mean to abandon it directly, but instead you could drop maintenance work after Sonata v4.0?

**Comment by greg0ire** [comment]
I'd be for entering maintenance mode (no new features) right now, and abandon the package after a while.

**Comment by core23** [comment]
We should leave a hint on the main page

**Comment by mvhirsch** [comment]
@core23 Can I help you with that? What should it look like? I guess you mean the README.md?

**Comment by core23** [comment]
The `README.md` file is autogenerated by the dev-kit. Maybe we could remove this project from it and the file by hand.

**Comment by jordisala1991** [comment]
I think dev-kit does nothing for this project: https://github.com/sonata-project/dev-kit/blob/master/config/projects.yml#L342

**Comment by Soullivaneuh** [comment]
I got @rande confirmation for making this project deprecated.

It will be done soon.

If anybody want to continue propel support, he cans feel free to fork this on another namespace.

**Comment by Soullivaneuh** [comment]
The project is now deprecated.
